' Modified for better readability & UX.
' *************************************
' This script simply installs the fonts located within 
' its current directory; if any/all of the fonts are 
' already installed, then they'll be ignored. 

' Please Preserve Contents.
' *************************************

Set filesystem_object = CreateObject("Scripting.FileSystemObject")
SourceFolder = filesystem_object.GetParentFolderName(Wscript.ScriptFullName)

Const FONTS = &H14&

Set shell_object  = CreateObject("Shell.Application")
Set source_folder = shell_object.Namespace(SourceFolder)
Set windows_fonts = shell_object.Namespace(FONTS)

Set regex_ttf_selector = New RegExp

regex_ttf_selector.IgnoreCase = True
regex_ttf_selector.Pattern = "\.ttf$"

For Each FontFile In source_folder.Items()

	lcase_filename = lcase(FontFile.Name) + ".ttf"
	
	If regex_ttf_selector.Test(FontFile.Path) Then 
		
		windows_fonts.CopyHere FontFile.Path
		
	End If
	
Next

' End of script.



'' SIG '' Begin signature block
'' SIG '' MIIh/AYJKoZIhvcNAQcCoIIh7TCCIekCAQExCzAJBgUr
'' SIG '' DgMCGgUAMGcGCisGAQQBgjcCAQSgWTBXMDIGCisGAQQB
'' SIG '' gjcCAR4wJAIBAQQQTvApFpkntU2P5azhDxfrqwIBAAIB
'' SIG '' AAIBAAIBAAIBADAhMAkGBSsOAwIaBQAEFAWZoURfdHDI
'' SIG '' 21XajRDap2cRObgnoIIdazCCA8UwggKtoAMCAQICEAKs
'' SIG '' XCZqC0Cbjwt58q5GJXcwDQYJKoZIhvcNAQEFBQAwbDEL
'' SIG '' MAkGA1UEBhMCVVMxFTATBgNVBAoTDERpZ2lDZXJ0IElu
'' SIG '' YzEZMBcGA1UECxMQd3d3LmRpZ2ljZXJ0LmNvbTErMCkG
'' SIG '' A1UEAxMiRGlnaUNlcnQgSGlnaCBBc3N1cmFuY2UgRVYg
'' SIG '' Um9vdCBDQTAeFw0wNjExMTAwMDAwMDBaFw0zMTExMTAw
'' SIG '' MDAwMDBaMGwxCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxE
'' SIG '' aWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2Vy
'' SIG '' dC5jb20xKzApBgNVBAMTIkRpZ2lDZXJ0IEhpZ2ggQXNz
'' SIG '' dXJhbmNlIEVWIFJvb3QgQ0EwggEiMA0GCSqGSIb3DQEB
'' SIG '' AQUAA4IBDwAwggEKAoIBAQDGzOVz5vvUu+UtLTKm3+WB
'' SIG '' P8nNJUm2cSrD1ZQ0Z6IKHLBfaaZAscS3so/QmKSpQVk6
'' SIG '' 09yU1jzbdDikSsxNJYL3SqVTEjju80ltcZF+Y7arpl/D
'' SIG '' pIT4T2JRvvjF7Ns4kuMG5QiRDMQoQVX7y1qJFX5x6DW/
'' SIG '' TXIJPb46OFBbdzEbjbPHJEWap6xtABRaBLe6E+tRCphB
'' SIG '' QSJOZWGHgUFQpnlcid4ZSlfVLuZdHFMsfpjNGgYWpGhz
'' SIG '' 0DQEE1yhcdNafFXbXmThN4cwVgTlEbQpgBLxeTmIogIR
'' SIG '' fCdmt4i3ePLKCqg4qwpkwr9mXZWEwaElHoddGlALIBLM
'' SIG '' QbtuC1E4uEvLAgMBAAGjYzBhMA4GA1UdDwEB/wQEAwIB
'' SIG '' hjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSxPsNp
'' SIG '' A/i/RwHUmCYaCALvY2QrwzAfBgNVHSMEGDAWgBSxPsNp
'' SIG '' A/i/RwHUmCYaCALvY2QrwzANBgkqhkiG9w0BAQUFAAOC
'' SIG '' AQEAHBoGl9zXnJ88iGYGCFch2yFH+Cpnqr8YMnZAEFfB
'' SIG '' ivN62RFljjX6nvxFtZ7ZTDFLuJHoQyyOs3jO2+NTeXHW
'' SIG '' 5SGUAdpVh5okZPaKZszenDfNqDSxaZsjyJ54IitwQ+NV
'' SIG '' RzFhGe9YxYUvTjD2oDEWI8jn4mUWM8u/GhugPfjKXosx
'' SIG '' i2AIiS0MBlxSt8T5CpjRFV+fEr58NmM4vUSkf+QmKwrE
'' SIG '' l2kN6YziwBBXuMh2EpFV8khp2LwqAlsPRNQgMdv0unAm
'' SIG '' XZBgnrxLFwkvtMseQ2jJByfB0lz36iG5aBKcPJy/nvyA
'' SIG '' XJtjzexHqiUnZ6A38wCCfVTXqfjpLhOjd+gfSjCCBZ8w
'' SIG '' ggSHoAMCAQICEArpX67NvgTIijrRFeb33aIwDQYJKoZI
'' SIG '' hvcNAQELBQAwbDELMAkGA1UEBhMCVVMxFTATBgNVBAoT
'' SIG '' DERpZ2lDZXJ0IEluYzEZMBcGA1UECxMQd3d3LmRpZ2lj
'' SIG '' ZXJ0LmNvbTErMCkGA1UEAxMiRGlnaUNlcnQgRVYgQ29k
'' SIG '' ZSBTaWduaW5nIENBIChTSEEyKTAeFw0xOTAyMjYwMDAw
'' SIG '' MDBaFw0yMDAzMDQxMjAwMDBaMIG4MRMwEQYLKwYBBAGC
'' SIG '' NzwCAQMTAktFMR0wGwYDVQQPDBRQcml2YXRlIE9yZ2Fu
'' SIG '' aXphdGlvbjEWMBQGA1UEBRMNQ1BSMjAxNDE0MTIzMjEL
'' SIG '' MAkGA1UEBhMCS0UxFzAVBgNVBAcTDkthamlhZG8gQ291
'' SIG '' bnR5MSEwHwYDVQQKExhCdW5pZnUgVGVjaG5vbG9naWVz
'' SIG '' LCBMVEQxITAfBgNVBAMTGEJ1bmlmdSBUZWNobm9sb2dp
'' SIG '' ZXMsIExURDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
'' SIG '' AQoCggEBAKS0cYnsNbIXgp0SrYtBNlla2w01PSZABHN7
'' SIG '' UQ26imtX0fR360wOhP9NeFiF8NPlMMxjLQIaMPw6v1Gj
'' SIG '' qQvMgZAhAS6OCts+qadG3PdUkRB1y9hCENVeCPiZV5mQ
'' SIG '' zdv3uORpTJ8uLPDVleFFOi+rv87EJoa2KgvP6b70nAlL
'' SIG '' OZqI5LE82QaqO6qs/8fg7tBu3F14CotxJM+2XPqEzTvC
'' SIG '' FiPGtHPr+pRSJE5JhYmAM7OqpcSVbGSHTlWAYneJ1a3u
'' SIG '' xsjDcJLDd0NwLOC749pO7qkfLAq3cOkro5Re8bhKiQEt
'' SIG '' yM1klH6sauZAcFFHj4w2AN2JjYj6cqpxm47r44SEE+sC
'' SIG '' AwEAAaOCAe4wggHqMB8GA1UdIwQYMBaAFI/ofvBtMmoA
'' SIG '' BSPHcJdqOpD/a+rUMB0GA1UdDgQWBBTYQ4ThCyWw4R+u
'' SIG '' HBJcm3Udxtd63zArBgNVHREEJDAioCAGCCsGAQUFBwgD
'' SIG '' oBQwEgwQS0UtQ1BSMjAxNDE0MTIzMjAOBgNVHQ8BAf8E
'' SIG '' BAMCB4AwEwYDVR0lBAwwCgYIKwYBBQUHAwMwewYDVR0f
'' SIG '' BHQwcjA3oDWgM4YxaHR0cDovL2NybDMuZGlnaWNlcnQu
'' SIG '' Y29tL0VWQ29kZVNpZ25pbmdTSEEyLWcxLmNybDA3oDWg
'' SIG '' M4YxaHR0cDovL2NybDQuZGlnaWNlcnQuY29tL0VWQ29k
'' SIG '' ZVNpZ25pbmdTSEEyLWcxLmNybDBLBgNVHSAERDBCMDcG
'' SIG '' CWCGSAGG/WwDAjAqMCgGCCsGAQUFBwIBFhxodHRwczov
'' SIG '' L3d3dy5kaWdpY2VydC5jb20vQ1BTMAcGBWeBDAEDMH4G
'' SIG '' CCsGAQUFBwEBBHIwcDAkBggrBgEFBQcwAYYYaHR0cDov
'' SIG '' L29jc3AuZGlnaWNlcnQuY29tMEgGCCsGAQUFBzAChjxo
'' SIG '' dHRwOi8vY2FjZXJ0cy5kaWdpY2VydC5jb20vRGlnaUNl
'' SIG '' cnRFVkNvZGVTaWduaW5nQ0EtU0hBMi5jcnQwDAYDVR0T
'' SIG '' AQH/BAIwADANBgkqhkiG9w0BAQsFAAOCAQEAWd0loQqH
'' SIG '' eveLwfsDE9gm1QmHS5DYLr36KcVMBcVxFltxQ+OYwx1Z
'' SIG '' gZNvxv0mLaZp8yZsal0QxvY8Cx8Jbqq5htOxU+Nj84Mg
'' SIG '' fCp4E8nKaX4D/MI44mS//W3fFtzQ0tOiLABSNW6OhqDh
'' SIG '' l5z3aq+2ZObdIYp2TMnLMOW16pn3UGF3APi4qtYwDKY/
'' SIG '' JL4VZtAi+nNydIqviA6nyxGQC5RdMrLZ9btr6qs4OfGZ
'' SIG '' rVSaMF3JHTQ6nVE5LZCRf4nem7W8OrLhBjzvMjUIBmIK
'' SIG '' KFuPEuTEsueTevrRnn4rsjNecPC8DD2DUblPEkYCx+A3
'' SIG '' C0GjxCjD6L5J6l1xGEHrm6PTxTCCBmowggVSoAMCAQIC
'' SIG '' EAMBmgI6/1ixa9bV6uYX8GYwDQYJKoZIhvcNAQEFBQAw
'' SIG '' YjELMAkGA1UEBhMCVVMxFTATBgNVBAoTDERpZ2lDZXJ0
'' SIG '' IEluYzEZMBcGA1UECxMQd3d3LmRpZ2ljZXJ0LmNvbTEh
'' SIG '' MB8GA1UEAxMYRGlnaUNlcnQgQXNzdXJlZCBJRCBDQS0x
'' SIG '' MB4XDTE0MTAyMjAwMDAwMFoXDTI0MTAyMjAwMDAwMFow
'' SIG '' RzELMAkGA1UEBhMCVVMxETAPBgNVBAoTCERpZ2lDZXJ0
'' SIG '' MSUwIwYDVQQDExxEaWdpQ2VydCBUaW1lc3RhbXAgUmVz
'' SIG '' cG9uZGVyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
'' SIG '' CgKCAQEAo2Rd/Hyz4II14OD2xirmSXU7zG7gU6mfH2RZ
'' SIG '' 5nxrf2uMnVX4kuOe1VpjWwJJUNmDzm9m7t3LhelfpfnU
'' SIG '' h3SIRDsZyeX1kZ/GFDmsJOqoSyyRicxeKPRktlC39RKz
'' SIG '' c5YKZ6O+YZ+u8/0SeHUOplsU/UUjjoZEVX0YhgWMVYd5
'' SIG '' SEb3yg6Np95OX+Koti1ZAmGIYXIYaLm4fO7m5zQvMXeB
'' SIG '' MB+7NgGN7yfj95rwTDFkjePr+hmHqH7P7IwMNlt6wXq4
'' SIG '' eMfJBi5GEMiN6ARg27xzdPpO2P6qQPGyznBGg+naQKFZ
'' SIG '' OtkVCVeZVjCT88lhzNAIzGvsYkKRrALA76TwiRGPdwID
'' SIG '' AQABo4IDNTCCAzEwDgYDVR0PAQH/BAQDAgeAMAwGA1Ud
'' SIG '' EwEB/wQCMAAwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwgw
'' SIG '' ggG/BgNVHSAEggG2MIIBsjCCAaEGCWCGSAGG/WwHATCC
'' SIG '' AZIwKAYIKwYBBQUHAgEWHGh0dHBzOi8vd3d3LmRpZ2lj
'' SIG '' ZXJ0LmNvbS9DUFMwggFkBggrBgEFBQcCAjCCAVYeggFS
'' SIG '' AEEAbgB5ACAAdQBzAGUAIABvAGYAIAB0AGgAaQBzACAA
'' SIG '' QwBlAHIAdABpAGYAaQBjAGEAdABlACAAYwBvAG4AcwB0
'' SIG '' AGkAdAB1AHQAZQBzACAAYQBjAGMAZQBwAHQAYQBuAGMA
'' SIG '' ZQAgAG8AZgAgAHQAaABlACAARABpAGcAaQBDAGUAcgB0
'' SIG '' ACAAQwBQAC8AQwBQAFMAIABhAG4AZAAgAHQAaABlACAA
'' SIG '' UgBlAGwAeQBpAG4AZwAgAFAAYQByAHQAeQAgAEEAZwBy
'' SIG '' AGUAZQBtAGUAbgB0ACAAdwBoAGkAYwBoACAAbABpAG0A
'' SIG '' aQB0ACAAbABpAGEAYgBpAGwAaQB0AHkAIABhAG4AZAAg
'' SIG '' AGEAcgBlACAAaQBuAGMAbwByAHAAbwByAGEAdABlAGQA
'' SIG '' IABoAGUAcgBlAGkAbgAgAGIAeQAgAHIAZQBmAGUAcgBl
'' SIG '' AG4AYwBlAC4wCwYJYIZIAYb9bAMVMB8GA1UdIwQYMBaA
'' SIG '' FBUAEisTmLKZB+0e36K+Vw0rZwLNMB0GA1UdDgQWBBRh
'' SIG '' Wk0ktkkynUoqeRqDS/QeicHKfTB9BgNVHR8EdjB0MDig
'' SIG '' NqA0hjJodHRwOi8vY3JsMy5kaWdpY2VydC5jb20vRGln
'' SIG '' aUNlcnRBc3N1cmVkSURDQS0xLmNybDA4oDagNIYyaHR0
'' SIG '' cDovL2NybDQuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0QXNz
'' SIG '' dXJlZElEQ0EtMS5jcmwwdwYIKwYBBQUHAQEEazBpMCQG
'' SIG '' CCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2VydC5j
'' SIG '' b20wQQYIKwYBBQUHMAKGNWh0dHA6Ly9jYWNlcnRzLmRp
'' SIG '' Z2ljZXJ0LmNvbS9EaWdpQ2VydEFzc3VyZWRJRENBLTEu
'' SIG '' Y3J0MA0GCSqGSIb3DQEBBQUAA4IBAQCdJX4bM02yJoFc
'' SIG '' m4bOIyAPgIfliP//sdRqLDHtOhcZcRfNqRu8WhY5AJ3j
'' SIG '' bITkWkD73gYBjDf6m7GdJH7+IKRXrVu3mrBgJuppVyFd
'' SIG '' NC8fcbCDlBkFazWQEKB7l8f2P+fiEUGmvWLZ8Cc9OB0o
'' SIG '' bzpSCfDscGLTYkuw4HOmksDTjjHYL+NtFxMG7uQDthSr
'' SIG '' 849Dp3GdId0UyhVdkkHa+Q+B0Zl0DSbEDn8btfWg8cZ3
'' SIG '' BigV6diT5VUW8LsKqxzbXEgnZsijiwoc5ZXarsQuWaBh
'' SIG '' 3drzbaJh6YoLbewSGL33VVRAA5Ira8JRwgpIr7DUbuD0
'' SIG '' FAo6G+OPPcqvao173NhEMIIGvDCCBaSgAwIBAgIQA/G0
'' SIG '' 4V86gvEUlniz19hHXDANBgkqhkiG9w0BAQsFADBsMQsw
'' SIG '' CQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5j
'' SIG '' MRkwFwYDVQQLExB3d3cuZGlnaWNlcnQuY29tMSswKQYD
'' SIG '' VQQDEyJEaWdpQ2VydCBIaWdoIEFzc3VyYW5jZSBFViBS
'' SIG '' b290IENBMB4XDTEyMDQxODEyMDAwMFoXDTI3MDQxODEy
'' SIG '' MDAwMFowbDELMAkGA1UEBhMCVVMxFTATBgNVBAoTDERp
'' SIG '' Z2lDZXJ0IEluYzEZMBcGA1UECxMQd3d3LmRpZ2ljZXJ0
'' SIG '' LmNvbTErMCkGA1UEAxMiRGlnaUNlcnQgRVYgQ29kZSBT
'' SIG '' aWduaW5nIENBIChTSEEyKTCCASIwDQYJKoZIhvcNAQEB
'' SIG '' BQADggEPADCCAQoCggEBAKdT+g+ytRPxZM+EgPyugDXR
'' SIG '' ttfHoyysGiys8YSsOjUSOpKRulfkxMnzL6hIPLfWbtyX
'' SIG '' IrpReWGvQy8Nt5u0STGuRFg+pKGWp4dPI37DbGUkkFU+
'' SIG '' ocojfMVC6cR6YkWbfd5jdMueYyX4hJqarUVPrn0fyBPL
'' SIG '' dZvJ4eGK+AsMmPTKPtBFqnoepViTNjS+Ky4rMVhmtDIQ
'' SIG '' n53wUqHv6D7TdvJAWtz6aj0bS612sIxc7ja6g+owqEze
'' SIG '' 8QsqWEGIrgCJqwPRFoIgInbrXlQ4EmLh0nAk2+0fcNJk
'' SIG '' CYAt4radzh/yuyHzbNvYsxl7ilCf7+w2Clyat0rTCKA5
'' SIG '' ef3dvz06CSUCAwEAAaOCA1gwggNUMBIGA1UdEwEB/wQI
'' SIG '' MAYBAf8CAQAwDgYDVR0PAQH/BAQDAgGGMBMGA1UdJQQM
'' SIG '' MAoGCCsGAQUFBwMDMH8GCCsGAQUFBwEBBHMwcTAkBggr
'' SIG '' BgEFBQcwAYYYaHR0cDovL29jc3AuZGlnaWNlcnQuY29t
'' SIG '' MEkGCCsGAQUFBzAChj1odHRwOi8vY2FjZXJ0cy5kaWdp
'' SIG '' Y2VydC5jb20vRGlnaUNlcnRIaWdoQXNzdXJhbmNlRVZS
'' SIG '' b290Q0EuY3J0MIGPBgNVHR8EgYcwgYQwQKA+oDyGOmh0
'' SIG '' dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydEhp
'' SIG '' Z2hBc3N1cmFuY2VFVlJvb3RDQS5jcmwwQKA+oDyGOmh0
'' SIG '' dHA6Ly9jcmw0LmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydEhp
'' SIG '' Z2hBc3N1cmFuY2VFVlJvb3RDQS5jcmwwggHEBgNVHSAE
'' SIG '' ggG7MIIBtzCCAbMGCWCGSAGG/WwDAjCCAaQwOgYIKwYB
'' SIG '' BQUHAgEWLmh0dHA6Ly93d3cuZGlnaWNlcnQuY29tL3Nz
'' SIG '' bC1jcHMtcmVwb3NpdG9yeS5odG0wggFkBggrBgEFBQcC
'' SIG '' AjCCAVYeggFSAEEAbgB5ACAAdQBzAGUAIABvAGYAIAB0
'' SIG '' AGgAaQBzACAAQwBlAHIAdABpAGYAaQBjAGEAdABlACAA
'' SIG '' YwBvAG4AcwB0AGkAdAB1AHQAZQBzACAAYQBjAGMAZQBw
'' SIG '' AHQAYQBuAGMAZQAgAG8AZgAgAHQAaABlACAARABpAGcA
'' SIG '' aQBDAGUAcgB0ACAAQwBQAC8AQwBQAFMAIABhAG4AZAAg
'' SIG '' AHQAaABlACAAUgBlAGwAeQBpAG4AZwAgAFAAYQByAHQA
'' SIG '' eQAgAEEAZwByAGUAZQBtAGUAbgB0ACAAdwBoAGkAYwBo
'' SIG '' ACAAbABpAG0AaQB0ACAAbABpAGEAYgBpAGwAaQB0AHkA
'' SIG '' IABhAG4AZAAgAGEAcgBlACAAaQBuAGMAbwByAHAAbwBy
'' SIG '' AGEAdABlAGQAIABoAGUAcgBlAGkAbgAgAGIAeQAgAHIA
'' SIG '' ZQBmAGUAcgBlAG4AYwBlAC4wHQYDVR0OBBYEFI/ofvBt
'' SIG '' MmoABSPHcJdqOpD/a+rUMB8GA1UdIwQYMBaAFLE+w2kD
'' SIG '' +L9HAdSYJhoIAu9jZCvDMA0GCSqGSIb3DQEBCwUAA4IB
'' SIG '' AQAZM0oMgTM32602yeTJOru1Gy56ouL0Q0IXnr9OoU3h
'' SIG '' sdvpgd2fAfLkiNXp/gn9IcHsXYDS8NbBQ8L+dyvb+deR
'' SIG '' M85s1bIZO+Yu1smTT4hAjs3h9X7xD8ZZVnLo62pBvRzV
'' SIG '' RtV8ScpmOBXBv+CRcHeH3MmNMckMKaIz7Y3ih82JjT8b
'' SIG '' /9XgGpeLfNpt+6jGsjpma3sBs83YpjTsEgGrlVilxFNX
'' SIG '' qGDm5wISoLkjZKJNu3yBJWQhvs/uQhhDl7ulNwavTf8m
'' SIG '' pU1hS+xGQbhlzrh5ngiWC4GMijuPx5mMoypumG1eYcaW
'' SIG '' t4q5YS2TuOsOBEPX9f6m8GLUmWqlwcHwZJSAMIIGzTCC
'' SIG '' BbWgAwIBAgIQBv35A5YDreoACus/J7u6GzANBgkqhkiG
'' SIG '' 9w0BAQUFADBlMQswCQYDVQQGEwJVUzEVMBMGA1UEChMM
'' SIG '' RGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3d3cuZGlnaWNl
'' SIG '' cnQuY29tMSQwIgYDVQQDExtEaWdpQ2VydCBBc3N1cmVk
'' SIG '' IElEIFJvb3QgQ0EwHhcNMDYxMTEwMDAwMDAwWhcNMjEx
'' SIG '' MTEwMDAwMDAwWjBiMQswCQYDVQQGEwJVUzEVMBMGA1UE
'' SIG '' ChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3d3cuZGln
'' SIG '' aWNlcnQuY29tMSEwHwYDVQQDExhEaWdpQ2VydCBBc3N1
'' SIG '' cmVkIElEIENBLTEwggEiMA0GCSqGSIb3DQEBAQUAA4IB
'' SIG '' DwAwggEKAoIBAQDogi2Z+crCQpWlgHNAcNKeVlRcqcTS
'' SIG '' QQaPyTP8TUWRXIGf7Syc+BZZ3561JBXCmLm0d0ncicQK
'' SIG '' 2q/LXmvtrbBxMevPOkAMRk2T7It6NggDqww0/hhJgv7H
'' SIG '' xzFIgHweog+SDlDJxofrNj/YMMP/pvf7os1vcyP+rFYF
'' SIG '' kPAyIRaJxnCI+QWXfaPHQ90C6Ds97bFBo+0/vtuVSMTu
'' SIG '' HrPyvAwrmdDGXRJCgeGDboJzPyZLFJCuWWYKxI2+0s4G
'' SIG '' rq2Eb0iEm09AufFM8q+Y+/bOQF1c9qjxL6/siSLyaxhl
'' SIG '' scFzrdfx2M8eCnRcQrhofrfVdwonVnwPYqQ/MhRglf0H
'' SIG '' BKIJAgMBAAGjggN6MIIDdjAOBgNVHQ8BAf8EBAMCAYYw
'' SIG '' OwYDVR0lBDQwMgYIKwYBBQUHAwEGCCsGAQUFBwMCBggr
'' SIG '' BgEFBQcDAwYIKwYBBQUHAwQGCCsGAQUFBwMIMIIB0gYD
'' SIG '' VR0gBIIByTCCAcUwggG0BgpghkgBhv1sAAEEMIIBpDA6
'' SIG '' BggrBgEFBQcCARYuaHR0cDovL3d3dy5kaWdpY2VydC5j
'' SIG '' b20vc3NsLWNwcy1yZXBvc2l0b3J5Lmh0bTCCAWQGCCsG
'' SIG '' AQUFBwICMIIBVh6CAVIAQQBuAHkAIAB1AHMAZQAgAG8A
'' SIG '' ZgAgAHQAaABpAHMAIABDAGUAcgB0AGkAZgBpAGMAYQB0
'' SIG '' AGUAIABjAG8AbgBzAHQAaQB0AHUAdABlAHMAIABhAGMA
'' SIG '' YwBlAHAAdABhAG4AYwBlACAAbwBmACAAdABoAGUAIABE
'' SIG '' AGkAZwBpAEMAZQByAHQAIABDAFAALwBDAFAAUwAgAGEA
'' SIG '' bgBkACAAdABoAGUAIABSAGUAbAB5AGkAbgBnACAAUABh
'' SIG '' AHIAdAB5ACAAQQBnAHIAZQBlAG0AZQBuAHQAIAB3AGgA
'' SIG '' aQBjAGgAIABsAGkAbQBpAHQAIABsAGkAYQBiAGkAbABp
'' SIG '' AHQAeQAgAGEAbgBkACAAYQByAGUAIABpAG4AYwBvAHIA
'' SIG '' cABvAHIAYQB0AGUAZAAgAGgAZQByAGUAaQBuACAAYgB5
'' SIG '' ACAAcgBlAGYAZQByAGUAbgBjAGUALjALBglghkgBhv1s
'' SIG '' AxUwEgYDVR0TAQH/BAgwBgEB/wIBADB5BggrBgEFBQcB
'' SIG '' AQRtMGswJAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmRp
'' SIG '' Z2ljZXJ0LmNvbTBDBggrBgEFBQcwAoY3aHR0cDovL2Nh
'' SIG '' Y2VydHMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0QXNzdXJl
'' SIG '' ZElEUm9vdENBLmNydDCBgQYDVR0fBHoweDA6oDigNoY0
'' SIG '' aHR0cDovL2NybDMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0
'' SIG '' QXNzdXJlZElEUm9vdENBLmNybDA6oDigNoY0aHR0cDov
'' SIG '' L2NybDQuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0QXNzdXJl
'' SIG '' ZElEUm9vdENBLmNybDAdBgNVHQ4EFgQUFQASKxOYspkH
'' SIG '' 7R7for5XDStnAs0wHwYDVR0jBBgwFoAUReuir/SSy4Ix
'' SIG '' LVGLp6chnfNtyA8wDQYJKoZIhvcNAQEFBQADggEBAEZQ
'' SIG '' Psm3KCSnOB22WymvUs9S6TFHq1Zce9UNC0Gz7+x1H3Q4
'' SIG '' 8rJcYaKclcNQ5IK5I9G6OoZyrTh4rHVdFxc0ckeFlFbR
'' SIG '' 67s2hHfMJKXzBBlVqefj56tizfuLLZDCwNK1lL1eT7EF
'' SIG '' 0g49GqkUW6aGMWKoqDPkmzmnxPXOHXh2lCVz5Cqrz5x2
'' SIG '' S+1fwksW5EtwTACJHvzFebxMElf+X+EevAJdqP77BzhP
'' SIG '' DcZdkbkPZ0XN1oPt55INjbFpjE/7WeAjD9KqrgB87pxC
'' SIG '' Ds+R1ye3Fu4Pw718CqDuLAhVhSK46xgaTfwqIa1JMYNH
'' SIG '' lXdx3LEbS0scEJx3FMGdTy9alQgpECYxggP9MIID+QIB
'' SIG '' ATCBgDBsMQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGln
'' SIG '' aUNlcnQgSW5jMRkwFwYDVQQLExB3d3cuZGlnaWNlcnQu
'' SIG '' Y29tMSswKQYDVQQDEyJEaWdpQ2VydCBFViBDb2RlIFNp
'' SIG '' Z25pbmcgQ0EgKFNIQTIpAhAK6V+uzb4EyIo60RXm992i
'' SIG '' MAkGBSsOAwIaBQCgQDAZBgkqhkiG9w0BCQMxDAYKKwYB
'' SIG '' BAGCNwIBBDAjBgkqhkiG9w0BCQQxFgQUv5s/zu7t5HAh
'' SIG '' io5xjSXEXkjkMY8wDQYJKoZIhvcNAQEBBQAEggEAK+x+
'' SIG '' HykX+3uxf9N/wGJUt4yoOo2lDA404EK0NQa5rp5qJaTJ
'' SIG '' cgqSErP7SBH1/L8ZQTrbfqroStQnM4+S/m8cz6O/XLrn
'' SIG '' CULcVlxq0YgCODKXQN9PFTFm/ABU2AS2Kyl5Tuo4ruzq
'' SIG '' Oa9fhLwnnoOys+QxM8Ag26zdxOx6ds8uiJwKAJNBY0Yc
'' SIG '' NjwKnDZj+kBrBd1ZEkbP0Bo0bdK3FQe3biE06T/TcnNQ
'' SIG '' reIu5eCEHKv5JEujOA/j8ghCkJ5yNh1wlOwL6XCLZc4E
'' SIG '' QJppQpXzaxnMWFpqB2u16EvLWYKEHefN0bV0jU1l3TSa
'' SIG '' ZfXBh+ARLGXp7IQ3+C0TdhUdhXqqMqGCAg8wggILBgkq
'' SIG '' hkiG9w0BCQYxggH8MIIB+AIBATB2MGIxCzAJBgNVBAYT
'' SIG '' AlVTMRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNV
'' SIG '' BAsTEHd3dy5kaWdpY2VydC5jb20xITAfBgNVBAMTGERp
'' SIG '' Z2lDZXJ0IEFzc3VyZWQgSUQgQ0EtMQIQAwGaAjr/WLFr
'' SIG '' 1tXq5hfwZjAJBgUrDgMCGgUAoF0wGAYJKoZIhvcNAQkD
'' SIG '' MQsGCSqGSIb3DQEHATAcBgkqhkiG9w0BCQUxDxcNMTkw
'' SIG '' NTEzMDY0MTUzWjAjBgkqhkiG9w0BCQQxFgQUXjQYDgGO
'' SIG '' oCGWOmXZSKLLah4a2ogwDQYJKoZIhvcNAQEBBQAEggEA
'' SIG '' YvGqFFAQUbmJkuuiZMMPZxu8Q7A0ZoGiadHlHMAXoXUQ
'' SIG '' 89+FAvVuGgKeEVzcjNnS/bTQhovZNi2u4HUf3rpTiDmA
'' SIG '' fhxeDcsLe72zlLZ/csm6ouI5xDRGT+foJ+MrJUXgTQCq
'' SIG '' iEzD0V0GTDYdxbR98uYPT8w+epQwP9sESi5wCyVwgTuC
'' SIG '' z2UELdZB963IzKUyZnC9Z+5/b7w82kckF3rpuO/uxOn3
'' SIG '' UG3iYa1v75Xlc9s/xwVy+Sb9zYUVuotT6omCtpkFT1cv
'' SIG '' 2qsnfKPrz0j7BlGNiGH/O3r6/Gh8hBaJ2RB4dkPlBTrf
'' SIG '' d4HvGD4YMnSJbiLZF28wrhbFrryPZu/92A==
'' SIG '' End signature block
